# Generated by Django 5.2 on 2025-04-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_followers'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='products.product'),
        ),
    ]
