# Generated by Django 5.2 on 2025-04-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Online Shop', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
