# Generated by Django 5.2 on 2025-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='OnlineShop', max_length=255),
        ),
    ]
