# Generated by Django 5.1.6 on 2025-04-28 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=100)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket'), ('Basketball', 'Basketball')], default='Football', max_length=50)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('league_code', models.CharField(default='XYZ', max_length=12, unique=True)),
                ('league_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10)),
                ('gameweek', models.IntegerField(default=1)),
                ('users', models.ManyToManyField(blank=True, related_name='leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='User', max_length=100)),
                ('formation_name', models.CharField(default='3-3-3', max_length=100)),
                ('position_coordinates', models.JSONField(default=dict)),
                ('position', models.CharField(default='DEF', max_length=50)),
                ('team', models.CharField(default='Team', max_length=100)),
                ('kickoff', models.CharField(default='2025-02-25T19:30:00Z', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('gameweek', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=20)),
                ('favorite_club', models.CharField(default='City', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_team', to='contests.player')),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to='contests.player')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vice_captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captain_team', to='contests.player')),
            ],
        ),
        migrations.CreateModel(
            name='CaptainViceCaptainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_history', to='contests.player')),
                ('vice_captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captain_history', to='contests.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.team')),
            ],
        ),
    ]
