"""
Django settings for fantasy_backend project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b1o%e)j6tvyrw797v+q$9jtb9khbstw0sumd=@0o4c5f(@lh+c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'contests',
    # 'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fantasy_backend.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Celery settings
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Use Redis as the broker
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_TIMEZONE = "UTC"

# Celery beat schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "update-player-scores": {
        "task": "your_app.tasks.update_player_scores_task",
        "schedule": crontab(hour=1, minute=0),  # Run daily at 1 AM UTC
    },
}

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'staticfiles_dev']
#STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'




WSGI_APPLICATION = 'fantasy_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'fantasy_db',
#         'USER': 'fantasy_sport',
#         'PASSWORD': '4851Cken',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#-----------------------------MPESA Settings-----------------------------
MPESA_CONSUMER_KEY = 'ScxV1ppbDXA38qfEWK6ldo7LAWXm9NWSLuBSUMzzislLEbjG'
MPESA_CONSUMER_SECRET = 'Gl4A1whyYJXmNxcObpjIGeRyBSdV1LI4dudBs0kwgoLkC0ML9swhsOPVLVbQGAc8'
MPESA_SHORTCODE = '174379'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_CALLBACK_URL = 'https://pangasquadii.digitlogic.co.ke/api/mpesa/callback/'
# MPESA_BASE_URL = 'https://api.safaricom.co.ke'
MPESA_BASE_URL = 'https://sandbox.safaricom.co.ke'

#-----------------------------B2C Payout Settings-----------------------------
# MPESA_INITIATOR_NAME = 'your_initiator_name'
# MPESA_B2C_SECURITY_CREDENTIAL = 'your_encrypted_security_credential'
# MPESA_B2C_SHORTCODE = 'your_paybill_shortcode'
MPESA_B2C_RESULT_URL = 'https://pangasquadii.digitlogic.co.ke/mpesa/b2c/result/'
MPESA_B2C_TIMEOUT_URL = 'https://pangasquadii.digitlogic.co.ke/mpesa/b2c/timeout/'

MPESA_INITIATOR_NAME = 'testapi'
MPESA_B2C_SECURITY_CREDENTIAL = 'Safaricom123!'  # For sandbox, this is not encrypted
MPESA_B2C_SHORTCODE = '600998'

CSRF_TRUSTED_ORIGINS = [
    'https://pangasquadii.digitlogic.co.ke',  # Allow local development
]



