# Generated by Django 5.2 on 2025-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seller_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
