# Generated by Django 5.2 on 2025-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='No Image', max_length=255, null=True),
        ),
    ]
