# Generated by Django 5.2 on 2025-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_alt_text_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Dresses', 'Dresses'), ('Jackets', 'Jackets'), ('Outerwear', 'Outerwear'), ('Sweaters', 'Sweaters'), ('T-shirts', 'T-shirts'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Suits', 'Suits'), ('Activewear', 'Activewear'), ('Sleepwear', 'Sleepwear'), ('Swimwear', 'Swimwear'), ('Lingerie', 'Lingerie'), ('Hats', 'Hats'), ('Bags', 'Bags'), ('Scarves', 'Scarves'), ('Belts', 'Belts'), ('Gloves', 'Gloves'), ('Socks', 'Socks'), ('Jewelry', 'Jewelry'), ('Eyewear', 'Eyewear'), ('Footwear', 'Footwear'), ('Kids', 'Kids'), ('Maternity', 'Maternity')], max_length=20),
        ),
    ]
