# Generated by Django 5.2 on 2025-04-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_subcategory_product_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='category_images/')),
                ('target', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('HomeGrown', 'HomeGrown'), ('NewArrival', 'NewArrival'), ('StaffPick', 'StaffPick'), ('General', 'General')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Dresses', 'Dresses'), ('Jackets', 'Jackets'), ('Outerwear', 'Outerwear'), ('Sweaters', 'Sweaters'), ('T-shirts', 'T-shirts'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Suits', 'Suits'), ('Activewear', 'Activewear'), ('Sleepwear', 'Sleepwear'), ('Swimwear', 'Swimwear'), ('Lingerie', 'Lingerie'), ('Hats', 'Hats'), ('Bags', 'Bags'), ('Scarves', 'Scarves'), ('Belts', 'Belts'), ('Gloves', 'Gloves'), ('Socks', 'Socks'), ('Jewelry', 'Jewelry'), ('Eyewear', 'Eyewear'), ('Footwear', 'Footwear'), ('Kids', 'Kids'), ('Maternity', 'Maternity')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
