# Generated by Django 5.2 on 2025-04-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_list',
        ),
    ]
