# Generated by Django 5.2 on 2025-04-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
