# Generated by Django 5.2 on 2025-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_brand_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='target',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Dresses', 'Dresses'), ('Jackets', 'Jackets'), ('Outerwear', 'Outerwear'), ('Sweaters', 'Sweaters'), ('T-shirts', 'T-shirts'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Suits', 'Suits'), ('Activewear', 'Activewear'), ('Sleepwear', 'Sleepwear'), ('Swimwear', 'Swimwear'), ('Lingerie', 'Lingerie'), ('Hats', 'Hats'), ('Bags', 'Bags'), ('Scarves', 'Scarves'), ('Belts', 'Belts'), ('Gloves', 'Gloves'), ('Socks', 'Socks'), ('Jewelry', 'Jewelry'), ('Eyewear', 'Eyewear'), ('Footwear', 'Footwear'), ('Kids', 'Kids'), ('Maternity', 'Maternity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Grey', 'Grey')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very good', 'Very good'), ('New with tags', 'New with tags')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('HomeGrown', 'HomeGrown'), ('NewArrival', 'NewArrival'), ('StaffPick', 'StaffPick'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='target',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=50),
        ),
    ]
