# Generated by Django 5.2 on 2025-04-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGrownBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('buttontext', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('slide_direction', models.CharField(choices=[('left', 'Slide from left'), ('right', 'Slide from right')], default='right', help_text='Animation direction when this slide appears', max_length=10)),
            ],
        ),
    ]
